# action.yml
name: "Cloudflare Web3 Gateway Update"
description: "Update a Cloudflare Web3 Gateway with a new IPFS Hash"
branding:
  icon: "type"
  color: "blue"
inputs:
  cid: # IPFS CID
    description: "IPFS CID"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cid }}
